plugins {
   id 'java'
}

dependencies {

   implementation project(':source:javalayers:businesslogiclayer')

   implementation group: 'jakarta.inject', name: 'jakarta.inject-api', version: jakartaInjectVersion

   implementation group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-base', version: hapiFhirVersion
   implementation group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-structures-r4', version: hapiFhirVersion
   implementation group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-server', version: hapiFhirVersion
}
